// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY5OmE0tUAEKUbhCuuVallQp6dZCwDLqk',
    appId: '1:378359158857:web:dce565c75cf0b21fb90798',
    messagingSenderId: '378359158857',
    projectId: 'chatapp-767f8',
    authDomain: 'chatapp-767f8.firebaseapp.com',
    storageBucket: 'chatapp-767f8.appspot.com',
    measurementId: 'G-W4RDSLEGV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnIG1WOMojrZU26NsdGZctanNUYqrO4Fk',
    appId: '1:378359158857:android:db36f6afa92b9ffbb90798',
    messagingSenderId: '378359158857',
    projectId: 'chatapp-767f8',
    storageBucket: 'chatapp-767f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3ZfdbqN8e_C02k2pGBoCEDv9XC8q8O8s',
    appId: '1:378359158857:ios:c97c9051d8fa9cbdb90798',
    messagingSenderId: '378359158857',
    projectId: 'chatapp-767f8',
    storageBucket: 'chatapp-767f8.appspot.com',
    androidClientId: '378359158857-h9um5hhh8rej130141ql0dlp0lc36v3e.apps.googleusercontent.com',
    iosClientId: '378359158857-bncohepd8esjntb62c5hbm0dma1be69a.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat2',
  );
}
